In [2]:
import numpy
import numpy as np

In [3]:
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
np.__version__

'1.19.4'

# Creating an Array

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# using tuple
import numpy as np

arr = np.array((1, 2, 3, 4, 5))

print(arr) 

[1 2 3 4 5]


In [7]:
# 0-D array
import numpy as np

arr = np.array(42)

print(arr) 

42


In [12]:
print(type(arr))
print(arr.ndim)

<class 'numpy.ndarray'>
0


In [13]:
# 1-D array
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [14]:
print(arr.ndim)

1


In [15]:
# 2-D array
arr = np.array([[1,2,3], [4,5,56]])
arr

array([[ 1,  2,  3],
       [ 4,  5, 56]])

In [16]:
print(arr.ndim)

2


In [17]:
# 3-D array


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr) 

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [18]:
print(arr.ndim)

3


In [66]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [67]:
a.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# n - dimensional array

In [19]:


arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim) 

[[[[[1 2 3 4]]]]]
number of dimensions : 5


# array indexing

In [20]:
# array indexing

arr = np.array([1, 2, 3, 4])

print(arr[0]) 

1


In [21]:


arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) 

7


In [22]:


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st dim: ', arr[0, 1]) 

2nd element on 1st dim:  2


In [23]:


arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('5th element on 2nd dim: ', arr[1, 4]) 

5th element on 2nd dim:  10


In [26]:


arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print(arr[0, 1, 2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [27]:
# negative indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1]) 

Last element from 2nd dim:  10


In [28]:
# array slicing


arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5]) 

[2 3 4 5]


In [29]:

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:4]) 

[1 2 3 4]


# numpy data types

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype) 

int64


In [33]:
arr = np.array([1,2.5,5,'baatu'])
print(arr.dtype)

<U32


In [34]:
print(arr)

['1' '2.5' '5' 'baatu']


# converting datatypes on existing array

In [35]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype) 

[1 2 3]
int32


In [36]:

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype) 

[ True False  True]
bool


In [37]:
arr

array([1, 0, 3])

In [40]:
arr[0]=42

In [41]:
arr

array([42,  0,  3])

# array shape

In [42]:
arr = np.array([1, 0, 3])
print(arr.shape)

(3,)


In [43]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape) 

(2, 4)


# Array Reshape

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr) 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Reshape From 1-D to 3-D

In [45]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr) 

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [46]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x) 

1
2
3


In [47]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x) 

[1 2 3]
[4 5 6]


In [48]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  for y in x:
    for z in y:
      print(z) 

1
2
3
4
5
6
7
8
9
10
11
12


In [49]:
#joining an array

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [54]:
# stacking array
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

[[1 4]
 [2 5]
 [3 6]]


In [62]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=0)

print(arr) 

[[1 2 3]
 [4 5 6]]


In [63]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr) 

[1 2 3 4 5 6]


In [64]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr) 

[[1 2 3]
 [4 5 6]]
